ElectionApp/Models/CastVote.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ElectionApp.Models
{
    public class CastVote
    {

        //Associate logged in user with Voter
        [Key]
        [Column(Order = 1)]
        public string VoterId { get; set; }
        public ApplicationUser Voter { get; private set; }

        //Party Info
        [Key]
        [Column(Order = 2)]
        public int PartyId { get; set; }
        public Party Party { get; private set; }

        public CastVote()
        {

        }

        public CastVote(Party party, ApplicationUser voter)
        {
            Party = party ?? throw new ArgumentNullException("party");

            if (voter == null)
                throw new ArgumentNullException("voter");
            Voter = voter;

        }

    }
}

ElectionApp/ViewModels/CastVotesViewModel.cs
using ElectionApp.Models;
using System.Collections.Generic;


namespace ElectionApp.ViewModels
{
    public class CastVotesViewModel
    {
        public Party Party { get; set; }

        public CastVote CastVote { get; set; }

        public int PartyId { get; set; }

        public IEnumerable<Party> Parties { get; set; }
        public string SearchTerm { get; set; }
    }
}

ElectionApp/Controllers/CastVotesController.cs
using ElectionApp.Models;
using ElectionApp.ViewModels;
using Microsoft.AspNet.Identity;
using System.Linq;
using System.Web.Mvc;
using ElectionApp.Persistance;


namespace ElectionApp.Controllers
{
    [Authorize]
    public class CastVotesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UnitOfWork _unitOfWork;          

        public CastVotesController()
        {
            _context = new ApplicationDbContext();
            _unitOfWork = new UnitOfWork(_context);
        }


        public ActionResult CastAVote(string query = null)
        {
            var regParties = _context.Parties.ToList();

            if (!string.IsNullOrWhiteSpace(query))
            { 
                regParties = regParties.Where(p =>
                    p.PartyName.Contains(query) ||
                    p.Acronym.Contains(query) ||
                    p.Representative.Contains(query)
                    ).ToList();
            }

            var viewModel = new CastVotesViewModel
            {
                Parties = regParties,
                SearchTerm = query
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CastVotesViewModel viewModel)
        {
            var userId = User.Identity.GetUserId();
            var partyId = viewModel.PartyId;

            if (_context.CastVotes.Any(v => v.VoterId == userId))
                return Content("You have already voted!");

            var castedVote = new CastVote
            {
                PartyId = partyId,
                VoterId = userId
            };

            _context.CastVotes.Add(castedVote);

            _unitOfWork.Complete(); 
            return RedirectToAction("Index", "Home");
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }
    }
}

ElectionApp/Views/CastVotes/CastAVote.cshtml
@model ElectionApp.ViewModels.CastVotesViewModel

@{
    ViewBag.Title = "CastAVote";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Cast A Vote</h2>

@using (Html.BeginForm("Create", "CastVotes"))
{

    @Html.AntiForgeryToken()
    <hr />
    <div class="form-horizontal">
        <div class="form-group">
            <div class="input-group" id ="searchParties">
                @Html.TextBoxFor(m => m.SearchTerm, new {@class = "form-control", autofocus = "autofocus" })
                <span class="input-group-addon">
                    <i class="glyphicon glyphicon-search"></i>
                </span>
            </div>
        </div>

        <ul class="itemCategory">
            @foreach (var party in Model.Parties)
            {
                <li>
                    <div class="itemClass">
                        <div class="itemGroup">
                            @party.Acronym
                        </div>
                        <div class="itemName">
                            @party.Representative
                        </div>
                    </div>
                    <div class="rdo-btn js-fav">
                        @Html.RadioButtonFor(m => m.PartyId, @party.Id, new { id = @party.PartyName })
                    </div>
                </li>
            }
        </ul>
    <div class="form-group">
        <div class="col-md-offset-1">
            <button type="submit" class="btn btn-primary"> Cast Vote </button>
        </div>
    </div>
    </div>

        }