ElectionApp/Models/FavouriteFood.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ElectionApp.Models
{
    public class FavouriteFood
    {
        public int Id { get; set; }

        public string VoterUserId { get; set; }
        public Voter Voter { get; set; }

        public int FoodId { get; set; }
        public Food Food { get; set; }

      }
}

ElectionApp/ViewModels/FavouriteFoodsViewModel.cs
using ElectionApp.Models;
using System.Collections.Generic;

namespace ElectionApp.ViewModels
{
    public class FavouriteFoodsViewModel
    {
        public int? FavouriteId { get; set; }

        public int SelectedFoodId { get; set; }

        public Food Food { get; set; }

        public Voter Voter { get; set; }

        public IEnumerable<Food> Foods { get; set; }
    }
}

ElectionApp/Controllers/Api/FavouriteFoodsController.cs
using ElectionApp.Models;
using Microsoft.AspNet.Identity;
using System.Linq;
using System.Web.Http;

namespace ElectionApp.Controllers.Api
{
    [Authorize]
    public class FavouriteFoodsController : ApiController
    {
        private readonly ApplicationDbContext _context;

        public FavouriteFoodsController()
        {
            _context = new ApplicationDbContext();
        }

        [HttpDelete]
        public IHttpActionResult Remove(int id)
        {
            var userId = User.Identity.GetUserId();

            var removeFood = _context.FavouriteFoods
                .Single(f => f.Id == id &&
                             f.VoterUserId == userId);

            _context.FavouriteFoods.Remove(removeFood);
            _context.SaveChanges();
            return Ok();
        }
    }
}

ElectionApp/Controllers/FavouriteFoodsController.cs
using System.Collections.Generic;
using ElectionApp.Dtos;
using ElectionApp.Models;
using ElectionApp.ViewModels;
using Microsoft.AspNet.Identity;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

namespace ElectionApp.Controllers
{
    [Authorize]
    public class FavouriteFoodsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public FavouriteFoodsController()
        {
            _context = new ApplicationDbContext();
        }


        public ActionResult Index()
        {
            return View(_context.FavouriteFoods
                                .Include(f => f.Food)
                                .ToList());
        }


        public ActionResult Create()
        {
           if (!RemainingFoodsList().Any())
            {
                return RedirectToAction("Index");
            }

            var viewModel = new FavouriteFoodsViewModel
            {
                Foods = RemainingFoodsList()
            };

            return View(viewModel);
        }


        [HttpPost]
        public ActionResult Create(FavouriteFoodsDto dto)
        {
            var userId = User.Identity.GetUserId();

            var favouriteFood = new FavouriteFood()
            {
                VoterUserId = userId,
                FoodId = dto.FoodId
            };

            _context.FavouriteFoods.Add(favouriteFood);
            _context.SaveChanges();

            return RedirectToAction("Create");

        }

        public ActionResult Edit(int id)
        {
            if (!RemainingFoodsList().Any())
            {
                return RedirectToAction("Index");
            }

            var viewModel = new FavouriteFoodsViewModel
            {
                FavouriteId = id,
                Foods = RemainingFoodsList()
            };

            return View("Edit", viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(FavouriteFoodsViewModel viewModel)
        { 
            var userId = User.Identity.GetUserId();

            var editFood = _context.FavouriteFoods
                                   .Single(f => f.Id == viewModel.FavouriteId &&
                                  f.VoterUserId == userId);

            editFood.VoterUserId = userId;
            editFood.FoodId = viewModel.SelectedFoodId;
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        public List<Food> RemainingFoodsList()
        {
            return _context.Foods
                           .Where(food => !_context.FavouriteFoods
                           .Any(f => f.FoodId == food.Id))
                           .ToList();
        }
    }
}

ElectionApp/Views/FavouriteFoods/Create.cshtml
@model ElectionApp.ViewModels.FavouriteFoodsViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>Select Favourite Food</h4>

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Voter.UserId)

        <ul class="itemCategory">
            @foreach (var food in Model.Foods)
            {
                <li>
                    <div class="itemClass">
                        <div class="itemGroup">
                            @food.Id
                        </div>
                        <div class="itemName">
                            @food.FoodName
                        </div>
                    </div>
                    <div class="form-group js-fav">
                        <button data-id="@food.Id" type="submit" 
                         class="btn btn-default js-toggle-fav"> Favourite? </button>
                    </div>
                </li>
            }
        </ul>
    </div>
<div>
    @Html.ActionLink("View Favourite Foods", "Index")
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $(document).ready(function () {
            $(".js-toggle-fav").click(function (e) {
                var fav = $(e.target);
                $.post('@Url.Action("Create","FavouriteFoods")', { foodId: fav.attr("data-id") })
                    .done(function () {
                        fav.parents("li").fadeOut(function () {
                            $(this).remove();
                        });
                    })
                    .fail(function () {
                        alert("Something failed!");
                    });
            });
            //AddFavouriteFoods();

        });
    </script>
}

ElectionApp/Views/FavouriteFoods/Edit.cshtml
@model ElectionApp.ViewModels.FavouriteFoodsViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>Edit Favourite Food </h4>


@using (Html.BeginForm())
{
    <hr />
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.FavouriteId)
    <div class="form-horizontal">

        <ul class="itemCategory">
            @foreach (var food in Model.Foods)
            {
                <li>
                    <div class="itemClass">
                        <div class="itemGroup">
                            @food.Id
                        </div>
                        <div class="itemName">
                            @food.FoodName
                        </div>
                    </div>
                    <div class="form-group js-fav">
                        @Html.RadioButtonFor(m => m.SelectedFoodId, @food.Id, new { id = @food.FoodName })
                    </div>
                </li>
            }
        </ul>
    </div>

    <div class="form-group">
        <div class="col-md-offset-1 col-md-11">
            <input type="submit" value="Save" class="btn btn-primary" />
        </div>
    </div>

}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ElectionApp/Views/FavouriteFoods/Index.cshtml
@model IEnumerable<ElectionApp.Models.FavouriteFood>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4> My Favourite Foods</h4>

<p>
    @Html.ActionLink("Add Favourite Food", "Create")
</p>
<ul class="itemCategory">

    @foreach (var item in Model)
    {
        <li>
            <div class="itemClass">
                <div class="itemGroup">
                    @item.Food.FoodName
                </div>
                <div class="itemName">
                    @item.Food.Id
                </div>
            </div>

            <div class="form-group js-fav">
                <div>
                    <a href="@Url.Action("Edit", "FavouriteFoods", new {id = item.Id})">
                        Change
                    </a>
                </div>
                <div>
                    <a href="#" class="js-remove" data-id="@item.Id"> 
                        Remove 
                    </a>
                </div>
            </div>
        </li>
    }
</ul>

@section Scripts {
    <script>
        $(document).ready(function () {

            ConfirmFoodRemoval();
        });

    </script>

}