ElectionApp/Controllers/FoodsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ElectionApp.Models;

namespace ElectionApp.Controllers
{
    public class FoodsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Foods
        public ActionResult Index()
        {
            return View(db.Foods.ToList());
        }

        // GET: Foods/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Food food = db.Foods.Find(id);
            if (food == null)
            {
                return HttpNotFound();
            }
            return View(food);
        }

        // GET: Foods/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Foods/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,FoodName")] Food food)
        {
            if (ModelState.IsValid)
            {
                db.Foods.Add(food);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(food);
        }

        // GET: Foods/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Food food = db.Foods.Find(id);
            if (food == null)
            {
                return HttpNotFound();
            }
            return View(food);
        }

        // POST: Foods/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FoodName")] Food food)
        {
            if (ModelState.IsValid)
            {
                db.Entry(food).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(food);
        }

        // GET: Foods/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Food food = db.Foods.Find(id);
            if (food == null)
            {
                return HttpNotFound();
            }
            return View(food);
        }

        // POST: Foods/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Food food = db.Foods.Find(id);
            db.Foods.Remove(food);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ElectionApp/Controllers/VotersController.cs
using AutoMapper;
using ElectionApp.Models;
using ElectionApp.Persistance;
using ElectionApp.ViewModels;
using Microsoft.AspNet.Identity;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

namespace ElectionApp.Controllers
{
    [Authorize]
    public class VotersController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UnitOfWork _unitOfWork;

        public VotersController()
        {
            _context = new ApplicationDbContext();
            _unitOfWork = new UnitOfWork(_context);
        }

        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();
           
            var voterInfo = _context.Voters
                              .Include(v => v.Race)
                              .Include(v => v.Province)
                              .Include(v => v.Municipality)
                              .Include(v => v.District)
                              .Single(v => v.UserId == userId);

            if (voterInfo == null)
                return HttpNotFound();

            return View(voterInfo);
        }

        [HttpGet]
        public ActionResult GetDistrictsByProvinceId(string provinceId)
        {
            var districts = _unitOfWork.Districts.GetDistrictsByProvinceId(provinceId);
            return Json(districts, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetMunicipalitiesByDistrictId(string districtId)
        {
            var districts = _unitOfWork.Municipalities.GetMunicipalitiesByDistrictId(districtId);
            return Json(districts, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult VoterInfo(Voter voter)
        {
            if (!ModelState.IsValid)
                return RedirectToAction("CreateVoter", voter);

            if (string.IsNullOrWhiteSpace(voter.UserId))
            {
                voter.UserId = User.Identity.GetUserId();
                _context.Voters.Add(voter);
            }
            else
            {
                var savedVoter = _context.Voters.Single(v => v.UserId == voter.UserId);
                Mapper.Map(voter, savedVoter);
            }
       
            _unitOfWork.Complete();

            return RedirectToAction("Index");
        }

        public ActionResult CreateVoter()
        {
            var raceName = _context.Races.ToList();
            var province = _unitOfWork.Provinces.GetProvinces();
            var district = _unitOfWork.Districts.GetDistrictsByProvinceId();
            var municipality = _unitOfWork.Municipalities.GetMunicipalitiesByDistrictId();

            var viewModel = new CreateVoterViewModel
            {
                Heading = "Create Voter",
                Races = raceName,
                Provinces = province,
                Districts = district,
                Municipalities = municipality
            };

            return View(viewModel);
        }

        public ActionResult EditVoter(string Id)
        {
            var voter = _context.Voters.SingleOrDefault(v => v.UserId == Id);

            if (voter == null)
                return HttpNotFound();

            var raceName = _context.Races.ToList();
            var province = _unitOfWork.Provinces.GetProvinces();
            var district = _unitOfWork.Districts.GetDistrictsByProvinceId();
            var municipality = _unitOfWork.Municipalities.GetMunicipalitiesByDistrictId();

            var viewModel = new CreateVoterViewModel
            {
                Voter = voter,
                Heading = "Edit Voter",
                Races = raceName,
                Provinces = province,
                Districts = district,
                Municipalities = municipality
            };

            return View("CreateVoter", viewModel);
        }


        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

    }
}

ElectionApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Election App</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/Content/cssjqryUi")
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
    

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Election App", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">

                @if (Request.IsAuthenticated)
                {
                    if (User.IsInRole("CanManageParties"))
                    {
                        <ul class="nav navbar-nav">
                            <li>@Html.ActionLink("Manage Parties", "Index", "Parties")</li>
                            <li>@Html.ActionLink("Manage Foods", "Index", "Foods")</li>
                            <li>@Html.ActionLink("Election Results", "Results", "ElectionResults")</li>
                        </ul>
                    }
                    else
                    {
                        <ul class="nav navbar-nav">
                            <li>@Html.ActionLink("Registration Details", "Index", "Voters")</li>
                            <li>@Html.ActionLink("Cast A Vote", "CastAVote", "CastVotes")</li>
                            <li>@Html.ActionLink("Favourite Foods", "Index", "FavouriteFoods")</li>
                        </ul>
                    }

                }
                else
                {
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Voter Registration", "CreateVoter", "Voters")</li>
                    </ul>
                }

                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>Election App &copy; @DateTime.Now.Year </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/electionApp")

    @RenderSection("scripts", required: false)
</body>
        </html>